language: cpp
compiler:
  - gcc
  - clang

sudo: required
dist: trusty

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/.ccache

env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=100M
    - CCACHE_CPP2=1
  matrix:
    - BUILD_VARIANT=basic
    - BUILD_VARIANT=vanilla
    - BUILD_VARIANT=full BLAS_VENDOR=All
#    - BUILD_WITH=clang BUILD_VARIANT=basic
#    - BUILD_WITH=clang BUILD_VARIANT=vanilla
#    - BUILD_WITH=clang BUILD_VARIANT=full BLAS_VENDOR=All
#    - BUILD_WITH=intel BUILD_VARIANT=basic
#    - BUILD_WITH=intel BUILD_VARIANT=vanilla
#    - BUILD_WITH=intel BUILD_VARIANT=full BLAS_VENDOR=All


addons:
  apt:
    packages:
      - libboost1.55-dev
      - libboost-date-time1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-program-options1.55-dev
      - libboost-system1.55-dev
      - libtbb-dev
      - libmpfr-dev
      - libopenblas-dev
      - liblapacke-dev
      - libeigen3-dev
      - libarmadillo-dev
#      - libtcmalloc-minimal4
#      - mtl

install:
  - if [ "${BUILD_WITH}" = "gnu" ]; then export CXX="g++" CC="gcc"; fi
  - if [ "${BUILD_WITH}" = "clang" ]; then export CXX="clang++" CC="clang"; fi
#  - if [ "${BUILD_WITH}" = "intel" ]; then ./contrib/setup_intel_toolchain.sh; export CXX="icpc" CC="icc"; fi

before_script:
  - mkdir ../calc-build-${BUILD_VARIANT}-${BUILD_WITH}
  - cd ../calc-build-${BUILD_VARIANT}-${BUILD_WITH}
  - cmake --version
  - cmake ../calc/

script: make
