set(HOST_CACHE_LINE_SIZE_TEST "${CMAKE_SOURCE_DIR}/cmake/test/host_cache_line_size.c")
try_run(HOST_CACHE_LINE_SIZE_RUN_RESULT HOST_CACHE_LINE_SIZE_COMPILE_RESULT
  "${CMAKE_BINARY_DIR}/tmp" ${HOST_CACHE_LINE_SIZE_TEST}
  CMAKE_FLAGS "-DCMAKE_BUILD_TYPE=Release"
  RUN_OUTPUT_VARIABLE HOST_CACHE_LINE_SIZE_RUN_OUTPUT)

if(HOST_CACHE_LINE_SIZE_COMPILE_RESULT)
  if(HOST_CACHE_LINE_SIZE_RUN_RESULT EQUAL 0)
    set(DEFAULT_CACHE_LINE_SIZE ${HOST_CACHE_LINE_SIZE_RUN_OUTPUT})
  endif()
endif()

